### ISSUE TITLE
Knockout-dragdrop works only in Chrome

### ISSUE THREAD

**Issue by rguderlei** [One-com/knockout-dragdrop#12]
We are trying to integrate knockout-dragdrop in a fairly standard application (knockout 2.2.1, jquery 1.11, sammy 0.7.4, the usual twitter bootstrap stuff). It works like a charm in chrome, but in Firefox and IE 11, the drag starts only after releasing mouse button. The drop occurs after a second click on the drop zone. Debugging didn't reveal any obvious interference by other event handlers.

Do you have any advice for us where to look for the problem? Are there any known issues?

Thank you in advance!

**Comment by troymolsberry** [comment]
FF has a long standing issue where it eats certain mouse events originating from elements that have overflow set to scroll, auto, or hidden. I would bet that people who experience FF issues with *any* DD library, including this one, are those with DD sources inside of elements with overflow set to something other than the default. 

I resolved this in our app by setting -moz-user-select: none on the scrollable element. Full credit for this solution goes to the author who mentions it in this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=339293

If I were to take credit for anything, it would be hunting through several decade old FF tickets to find this solution, and vetting out 20 other suggestions that did nothing to help.
