### ISSUE TITLE
Prevent Event Bubbling???

### ISSUE THREAD

**Issue by montymccune** [One-com/knockout-dragdrop#15]
I'm loving your library so far - great job! However, I'm finding that when I nest dragEvents.dragOver within another div that contains dragEvents.dragOver, the event bubbles up. It would be cool if there would be a way to set whether or not the event bubbles up the dom.

thanks again - Monty

**Comment by sunesimonsen** [comment]
I just ran into the same problem, so I guess it will be fixed pretty soon, as I need it solved for one of my own projects.

**Comment by sunesimonsen** [comment]
I look into the issue and I don't think it can be done without hurting the performance.
