### ISSUE TITLE
Supporting touch events

### ISSUE THREAD

**Issue by DenEwout** [One-com/knockout-dragdrop#19]
Hi,

I'm using knockout-dragdrop for a project of mine which requires support for touch-devices. This is sadly not supported by knockout-dragdrop.

I looked in the source code, would it be as easy to just add the correct events to the already present mouse events? (or perhaps create a simple mapping to have them map to one event?)

I'll fork to investigate/add this feature myself. But any help/tips would be appreciated.

Kind Regards,

@DenEwout

**Comment by stretch4x4** [comment]
Has anyone looked at this any further?
Currently in chrome on a windows touchscreen we can't click and drag as it just scrolls the container instead.
I guess I will have to have a closer look tomorrow..

**Comment by sunesimonsen** [comment]
No there has not been any attempts to support touch yet. At some point we
will need it at One.com and implement it, but we are of cause open to pull
request ;-)

Kind regards
Sune

**Comment by sunesimonsen** [comment]
#26 added initial touch support, there are still some limitations where you stop getting move events when the element you started the drag on is removed from the dom.
