### ISSUE TITLE
Drag a div doesn't work properly

### ISSUE THREAD

**Issue by discmaster** [One-com/knockout-dragdrop#21]
When making e.g. a div a dragZone, dragging will only work when dragging in a direction depending to where i clicked in the div. The onMouseMoveStartDrag-function calculates the distance only when mouse is over the element to drag. When clicking on the right side of the div and dragging to right, the dragDistance may not be reached and startDragging-function will not be called.
![Example](https://cloud.githubusercontent.com/assets/12410218/7586280/a808a5f6-f8ab-11e4-98a0-49e51bb8903f.png)

Edit: A fix could be to attach/detach the mousemove listener to document.body instead of element - but i've not tested consquences of this fix.

**Comment by sunesimonsen** [comment]
Thanks for the issue, I was thinking about fixing this, but forgot it again. I'll try to fix it this week.

**Comment by sunesimonsen** [comment]
Fixed in v2.0.1
