### ISSUE TITLE
Example page not up to date?

### ISSUE THREAD

**Issue by stretch4x4** [One-com/knockout-dragdrop#25]
It appears that the example page is not using the latest version of the library.

When I test the vertical scrolling in chrome it auto scrolls to the end, however when I run the same example locally with the latest version the behaviour is different.

I suspect somehow the demo is running on a previous version of the library but not entirely sure..

Would be great to update it.

**Comment by sunesimonsen** [comment]
I just updated it, sorry about that.

**Comment by stretch4x4** [comment]
Awesome, hopefully that helps a few people out :)
