### ISSUE TITLE
Touch: Make the drag start delay configurable

### ISSUE THREAD

**Issue by stretch4x4** [One-com/knockout-dragdrop#28]
I think the delay before dragging starts with touch needs to be configurable.
When testing on a windows 7 pc with a 22" touchscreen, in chrome this works fine, however in firefox it seems to trigger a bit slower and you end up right clicking before the drag starts.

On windows a press and hold is generally a right click and this period is configurable by the user.

**Comment by sunesimonsen** [comment]
I agree that is should be configurable, I just didn't get around to it.

**Comment by stretch4x4** [comment]
Cool,
Not really sure where to start on this one otherwise I would take a look.

**Comment by sunesimonsen** [comment]
I just added it: #1699783

**Comment by sunesimonsen** [comment]
I just implemented it 327db321d9911e7aae4075b09c65461f97659ad7 it will be released later today.

**Comment by stretch4x4** [comment]
Simple :)
