### ISSUE TITLE
Your example in your help file doesn't work

### ISSUE THREAD

**Issue by rhyous** [One-com/knockout-dragdrop#29]
The example page, while cool, is unfortunate in that it is huge. I tried to reproduce the simple example from the read me.

```
<!DOCTYPE html>
<html>

<head>
  <script data-require="jquery@2.1.3" data-semver="2.1.3" src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
  <script data-require="knockout@3.3.0" data-semver="3.3.0" src="http://cdnjs.cloudflare.com/ajax/libs/knockout/3.3.0/knockout-min.js"></script>
  <script type="text/javascript" src="./knockout.dragdrop.js"></script>
  <script>
    $(function() {
      var model = {
        source: ko.observableArray([
          'Declan',
          'Tessa',
          'Claire',
          'Violet',
          'Alice',
          'Mia',
          'Camille',
          'Aiden'
        ]),
        target: ko.observableArray(),
        drop: function(data, model) {
          model.source.remove(data);
          model.target.push(data);
        }
      };
      ko.applyBindings(model);
    })
  </script>
</head>

<body>
<h2>Drag from here</h2>
<ul data-bind="foreach: source">
    <li data-bind="text: $data, dragZone: { name: 'lists' }"></li>
</ul>

<h2>Drop here</h2>
<ul style="background-color: blue" data-bind="foreach: target, dropZone: { accepts: 'lists', drop: drop }">
    <li data-bind="text: $data"></li>
</ul>
</body>

</html>
```

Do you know what is wrong with the sample on your readme?

**Comment by sunesimonsen** [comment]
You need to be more specific than that. What is the problem you are experiencing, what is your setup, browser version etc.

**Comment by rhyous** [comment]
Problem: I drag and drop and nothing happens.
Chrome Version 43.0.2357.124 m
You did see I posted a full single file html file, right? It is pretty much a copy of the code snippets in your read me.

**Comment by sunesimonsen** [comment]
Just to be clear, is it this page that you can't get to work, or your own attempt:
http://one-com.github.io/knockout-dragdrop/examples/

**Comment by rhyous** [comment]
Uh, no. The example page with tons of examples does work. I started reverse engineering that, but there were too many examples.

Your readme file has a very small and simple code snippet. I was trying to get something more minimal than your example page so I went with the snippet on your readme. The basic most minimal example.

I posted the html of the failed example I am using as a single page html in the first post. I created this from the snippets in your readme.

**Comment by sunesimonsen** [comment]
Ahh I see, I'll see if I can get the time to make a minor example for you. I wish I had the time to improve the documentation - but that is unfortunately not the case.

**Comment by sunesimonsen** [comment]
@rhyous your example works, it is just because your drop zone has a height of 0, try setting the min-height and it will work.

**Comment by rhyous** [comment]
Thank you! The minimum height issue was the problem!
