### ISSUE TITLE
Drag preview element disappears if parent node is removed.

### ISSUE THREAD

**Issue by Tempurturtul** [One-com/knockout-dragdrop#37]
Here's my simplified use case involving nested lists:

```html
    <ul data-bind="template: { name: 'listTemplate', foreach: listEntry }">
    </ul>

    <!-- List template. -->
    <script type="text/html" id="listTemplate">
      <li>
        <!-- A normal list entry. -->
        <!-- ko ifnot: $data.contents -->
          <span data-bind="text: title,
                           dragZone: {
                             name: 'sortable'
                           },
                           dragEvents: {
                             accepts: 'sortable',
                             dragOver: $root.reorder
                           }"></span>
        <!-- /ko -->

        <!-- A folder list entry. -->
        <!-- ko if: $data.contents -->
          <span data-bind="text: title,
                           dragZone: {
                             name: 'sortable'
                           },
                           dragEvents: {
                             accepts: 'sortable',
                             dragOver: $root.reorder
                           }"></span>
          <ul class="folder-contents"
                data-bind="template: { name: 'listTemplate', foreach: contents }">
          </ul>
        <!-- /ko -->
      </li>
    </script>
```

`$root.reorder` works in much the same way as the `reorder` function in the examples, moving the `<li>` element to a new position when it hovers over a different `<li>` element.  The drag preview element created by knockout-dragdrop's `createCloneProxyElement` was appended as a child to the `<li>` element and is no longer visible when it is moved, even though the user may continue dragging as expected.

One solution is to place the dragdrop data-binds on the `<li>` elements, but that causes issues in my case due to the nested lists each with their own dragdrop data-binds.

Is there a reason why `createCloneProxyElement` appends the proxy element to the target element's parent node instead of the document body (a change which seems to resolve this issue)?

**Comment by mwoc** [comment]
The styling of the proxy element depends on where in the DOM it is, and as such we need it to be linked to the 'correct' parent. Maybe we can clone the parent instead, but what happens if someone removes _that_ element with another knockout binding :) Shadow dom perhaps?

**Comment by Tempurturtul** [comment]
Thanks for the answer and suggestion mwoc.  I've yet to work much with the Shadow DOM, but it [doesn't appear to be well enough supported](http://caniuse.com/#feat=shadowdom) to be a great solution at the moment, right?

After working on this some more, I've decided to just use a custom drag element as is demonstrated in the examples.  This resolves my use case very nicely as it's appended to the body instead of the element's parent.
